#! /bin/bash
rm -rf storage/cms/cache/*
rm -rf storage/cms/twig/*
rm -rf storage/framework/cache/*
rm -rf storage/temp/*
rm -rf storage/debugbar/*
message="$(date) $1"
git add -A && git commit -a -m "$message" && git push origin master && git status
