<?php
$CFG = array (
  'charsets' => 'cp1251 utf8 latin1',
  'lang' => 'en',
  'time_web' => '600',
  'time_cron' => '600',
  'backup_path' => 'backup/',
  'backup_url' => 'backup/',
  'only_create' => 'MRG_MyISAM MERGE HEAP MEMORY',
  'globstat' => 0,
  'my_host' => 'localhost',
  'my_port' => 3306,
  'my_user' => 'oktick',
  'my_pass' => '1c4f21c534b36c73e3d93be09122ebdc',
  'my_comp' => 0,
  'my_db' => '',
  'auth' => 'mysql cfg',
  'user' => '',
  'pass' => '',
  'confirm' => '30',
  'exitURL' => './',
  'outfile_path' => 'backup/',
  'outfile_size' => '64',
);
?>